name: Variable and Secrets

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: printing variable and secret
        run: |
          echo "The variable is: ${{vars.MY_VARIABLE}}"
          echo "The secret is: ${{secrets.CONNECTION_STRING}}"
